from __future__ import annotations

import csv
import html
from pathlib import Path

import typer
from rich.console import Console
from rich.table import Table

from draftcode.config import get_settings
from draftcode.pipeline import run_prediction

app = typer.Typer(help="NBA draft prediction agent CLI.")
console = Console()


@app.callback()
def root() -> None:
    """Run DraftCode commands."""


@app.command()
def predict(
    data_dir: Path = typer.Option(None, help="Directory containing prospects/draft_order/team_needs CSVs."),
    output: Path = typer.Option(None, help="CSV path for final predictions."),
    trace: Path = typer.Option(None, help="JSON path for decision trace."),
) -> None:
    settings = get_settings()
    resolved_data_dir = data_dir or settings.data_dir
    resolved_output = output or settings.output_dir / "predictions.csv"
    resolved_trace = trace or settings.output_dir / "trace.json"

    picks = run_prediction(resolved_data_dir, output=resolved_output, trace_path=resolved_trace)

    table = Table(title="DraftCode prediction run")
    table.add_column("Pick", justify="right")
    table.add_column("Team")
    table.add_column("Prospect")
    table.add_column("Conf.", justify="right")
    table.add_column("Score", justify="right")
    for pick in picks:
        table.add_row(
            str(pick.pick),
            pick.abbreviation,
            pick.prospect_name,
            f"{pick.confidence:.2f}",
            f"{pick.score:.3f}",
        )
    console.print(table)
    console.print(f"[green]Wrote predictions:[/green] {resolved_output}")
    console.print(f"[green]Wrote trace:[/green] {resolved_trace}")


@app.command("validate-output")
def validate_output(
    predictions: Path = typer.Option(..., help="Predictions CSV generated by the agent."),
    expected_picks: int = typer.Option(30, help="Expected number of first-round picks."),
) -> None:
    if not predictions.exists():
        raise typer.BadParameter(f"Predictions file does not exist: {predictions}")

    with predictions.open(newline="", encoding="utf-8") as handle:
        rows = list(csv.DictReader(handle))

    errors: list[str] = []
    if len(rows) != expected_picks:
        errors.append(f"expected {expected_picks} rows, found {len(rows)}")

    pick_numbers = [row.get("pick", "") for row in rows]
    prospect_ids = [row.get("prospect_id", "") for row in rows]
    required = ["pick", "team", "abbreviation", "prospect_id", "prospect_name", "reason"]

    if len(set(pick_numbers)) != len(pick_numbers):
        errors.append("duplicate pick numbers found")
    if len(set(prospect_ids)) != len(prospect_ids):
        errors.append("duplicate prospect IDs found")
    for index, row in enumerate(rows, start=1):
        missing = [field for field in required if not row.get(field)]
        if missing:
            errors.append(f"row {index} missing fields: {', '.join(missing)}")

    if errors:
        for error in errors:
            console.print(f"[red]error:[/red] {error}")
        raise typer.Exit(code=1)

    console.print(f"[green]ok:[/green] {predictions} passes submission shape checks")


@app.command("render-report")
def render_report(
    predictions: Path = typer.Option(..., help="Predictions CSV generated by the agent."),
    output: Path = typer.Option(Path("outputs/report.html"), help="HTML report path."),
) -> None:
    if not predictions.exists():
        raise typer.BadParameter(f"Predictions file does not exist: {predictions}")

    with predictions.open(newline="", encoding="utf-8") as handle:
        rows = list(csv.DictReader(handle))

    table_rows = "\n".join(
        "<tr>"
        f"<td>{html.escape(row.get('pick', ''))}</td>"
        f"<td>{html.escape(row.get('abbreviation', ''))}</td>"
        f"<td>{html.escape(row.get('prospect_name', ''))}</td>"
        f"<td><div class='bar'><span style='width:{float(row.get('confidence', 0)) * 100:.0f}%'></span></div>"
        f"{float(row.get('confidence', 0)):.2f}</td>"
        f"<td>{html.escape(row.get('reason', ''))}</td>"
        "</tr>"
        for row in rows
    )
    page = f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>DraftCode Prediction Report</title>
  <style>
    body {{ font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; margin: 32px; color: #161616; }}
    header {{ max-width: 960px; margin-bottom: 24px; }}
    h1 {{ margin: 0 0 8px; font-size: 32px; }}
    p {{ color: #555; }}
    table {{ width: 100%; border-collapse: collapse; font-size: 14px; }}
    th, td {{ border-bottom: 1px solid #ddd; padding: 10px 12px; text-align: left; vertical-align: top; }}
    th {{ background: #f4f6f8; color: #333; }}
    td:first-child, th:first-child {{ width: 56px; text-align: right; }}
    .bar {{ width: 88px; height: 8px; background: #e8edf2; border-radius: 999px; overflow: hidden; display: inline-block; margin-right: 8px; }}
    .bar span {{ display: block; height: 100%; background: #0f766e; }}
  </style>
</head>
<body>
  <header>
    <h1>DraftCode Prediction Report</h1>
    <p>Generated from the agent output. Use this as an offline roadshow fallback and audit view.</p>
  </header>
  <table>
    <thead>
      <tr><th>Pick</th><th>Team</th><th>Prospect</th><th>Confidence</th><th>Agent reason</th></tr>
    </thead>
    <tbody>
      {table_rows}
    </tbody>
  </table>
</body>
</html>
"""
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(page, encoding="utf-8")
    console.print(f"[green]Wrote report:[/green] {output}")


def main() -> None:
    app()


if __name__ == "__main__":
    main()
