from __future__ import annotations

from pathlib import Path

import pandas as pd
import streamlit as st

st.set_page_config(page_title="DraftCode NBA Draft Agent", layout="wide")

st.title("DraftCode NBA Draft Agent")
st.caption("Auditable pick predictions generated by the local agent pipeline.")

predictions_path = Path(st.query_params.get("predictions", "outputs/predictions.csv"))

if not predictions_path.exists():
    st.warning("No predictions file yet. Run `make predict` first.")
    st.stop()

df = pd.read_csv(predictions_path)

col1, col2, col3 = st.columns(3)
col1.metric("Predicted picks", len(df))
col2.metric("Avg confidence", f"{df['confidence'].mean():.2f}")
col3.metric("Lowest confidence", f"{df['confidence'].min():.2f}")

st.dataframe(
    df[["pick", "team", "prospect_name", "confidence", "score", "reason"]],
    use_container_width=True,
    hide_index=True,
)
