FROM public.ecr.aws/lambda/python:3.12

WORKDIR ${LAMBDA_TASK_ROOT}

COPY pyproject.toml README.md ./
COPY src ./src
COPY data/sample ./data/sample

RUN python -m pip install --no-cache-dir .

CMD ["draftcode.lambda_handler.handler"]
